# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('family_type', models.IntegerField(choices=[(0, 'FIRST RESPONDER'), (1, 'VOLUNTEER'), (2, 'USER')])),
            ],
        ),
        migrations.AlterField(
            model_name='pak',
            name='location',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pak',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AddField(
            model_name='family',
            name='pak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='api.Pak'),
        ),
    ]
