# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170917_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('completed_on', models.DateTimeField()),
                ('x_coord', models.FloatField()),
                ('y_coord', models.FloatField()),
                ('message', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Wolf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wolf', to='api.Family')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='api.Wolf'),
        ),
    ]
