# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170917_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='distance',
        ),
    ]
