# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_quest_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='x_coord',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='y_coord',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.IntegerField(choices=[(0, 'AVAILABLE'), (1, 'CLAIMED'), (2, 'COMPLETED')], default=0),
        ),
    ]
